name: Generar y Publicar Javadoc

on:
  push:
    branches:
      - stable

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generar Javadoc con Maven
        run: mvn javadoc:javadoc -DskipTests

      - name: Subir a GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'target/site/apidocs'

      - name: Desplegar
        uses: actions/deploy-pages@v4
