name: Generar y Publicar Javadoc

on:
  push:
    branches:
      - stable

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generar Javadoc con Maven
        # AJUSTE: Si tu pom.xml está dentro de una carpeta, Maven lo buscará ahí
        run: mvn javadoc:javadoc -DskipTests
        working-directory: ./tdd-en-proyectos-de-java-anmurog 

      - name: Subir a GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          # AJUSTE: También cambiamos la ruta de subida
          path: 'tdd-en-proyectos-de-java-anmurog/target/site/apidocs'

      - name: Desplegar
        uses: actions/deploy-pages@v4
